# Tema 1  - Matrices

Vamos a ver como crear una matriz utilizando la libreria numpy.

In [23]:
row = [1,2,3] #Crear fila.
row

[1, 2, 3]

In [24]:
Ccol = [1],[2],[3] #Crear columna

In [25]:
M = [[1,2,3],[4,5,6],[7,8,9]] #Crear matriz.
M

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [26]:
M[1][1]

5

In [27]:
M[0][0]

1

In [28]:
M[0]

[1, 2, 3]

In [29]:
M[0][1]

2

In [30]:
2*M

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [31]:
import numpy as np

In [32]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = complex)

In [33]:
M

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

In [34]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = float)
M

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [35]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [36]:
np.shape(M)

(3, 3)

In [37]:
A = np.array([[1,2],[3,4]])
B = np.array([[3,0],[1,-1]])

In [38]:
A+B

array([[4, 2],
       [4, 3]])

In [39]:
A.dot(B) #Producto matricial

array([[ 5, -2],
       [13, -4]])

In [40]:
A.transpose()

array([[1, 3],
       [2, 4]])

In [41]:
A.trace()

5

In [43]:
np.linalg.matrix_rank(A)

2

In [45]:
np.linalg.matrix_power(A,5)   

array([[1069, 1558],
       [2337, 3406]])

In [47]:
np.linalg.det(A)

-2.0000000000000004

In [48]:
np.linalg.inv(A).dot(A)

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [49]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [53]:
print(np.linalg.matrix_rank(x))
print(np.linalg.det(x))

2
-9.51619735392994e-16


In [54]:
np.linalg.inv(x)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])